import { IMedicalHistory } from '../models';

export const medicalHistoryData: IMedicalHistory[] = [
  {
    changedBy: 'User, Test',
    newValue: 'No',
    oldValue: null,
    parameterNames: ['p6ACRMeasured'],
    task: '',
    updatedOn: '15-Mar-2021 13:56',
    label: 'ACR measured',
    kind: 'Modified',
  },
  {
    changedBy: 'User, Test',
    newValue: 'No',
    oldValue: null,
    parameterNames: ['p6Infection'],
    task: '',
    updatedOn: '15-Mar-2021 13:56',
    label: 'Infection',
    kind: 'Modified',
  },
  {
    changedBy: 'User, Test',
    newValue: 'No',
    oldValue: null,
    parameterNames: ['p6PreviousRT'],
    task: '',
    updatedOn: '15-Mar-2021 13:56',
    label: 'Previous RT',
    kind: 'Modified',
  },
  {
    changedBy: 'User, Test',
    newValue: 'No',
    oldValue: null,
    parameterNames: ['p6Diabetes'],
    task: '',
    updatedOn: '15-Mar-2021 13:56',
    label: 'Diabetes',
    kind: 'Modified',
  },
  {
    changedBy: 'User, Test',
    newValue: 'No',
    oldValue: null,
    parameterNames: ['p6GFRMeasured'],
    task: '',
    updatedOn: '15-Mar-2021 13:56',
    label: 'GFR measured',
    kind: 'Modified',
  },
  {
    label: 'Positioning devices > Feet step > Incline',
    changedBy: 'User, Test',
    oldValue: null,
    newValue: '8',
    parameterNames: ['p6PositioningDevices'],
    task: 'CT simulation',
    updatedOn: '15-Mar-2021 15:16',
    kind: 'Modified',
  },
  {
    label: 'Positioning devices > Feet step > Index',
    changedBy: 'User, Test',
    oldValue: null,
    newValue: '7',
    parameterNames: ['p6PositioningDevices'],
    task: 'CT simulation',
    updatedOn: '15-Mar-2021 15:16',
    kind: 'Modified',
  },
  {
    label: 'Positioning devices > Feet step > Position',
    changedBy: 'User, Test',
    oldValue: '',
    newValue: 'C',
    parameterNames: ['p6PositioningDevices'],
    task: 'CT simulation',
    updatedOn: '15-Mar-2021 15:16',
    kind: 'Modified',
  },
  {
    label: 'Positioning devices > Feet step > Remark',
    changedBy: 'User, Test',
    oldValue: null,
    newValue: 'Test 123',
    parameterNames: ['p6PositioningDevices'],
    task: 'CT simulation',
    updatedOn: '15-Mar-2021 15:16',
    kind: 'Modified',
  },
  {
    label: 'Positioning devices > Knee step > Children > Device 1 > Position',
    changedBy: 'User, Test',
    oldValue: '',
    newValue: null,
    parameterNames: ['p6PositioningDevices'],
    task: 'CT simulation',
    updatedOn: '15-Mar-2021 15:16',
    kind: 'Modified',
  },
  {
    label:
      'Positioning devices > Thorax board > Children > Device 7 > Position',
    changedBy: 'User, Test',
    oldValue: '',
    newValue: null,
    parameterNames: ['p6PositioningDevices'],
    task: 'CT simulation',
    updatedOn: '15-Mar-2021 15:16',
    kind: 'Modified',
  },
  {
    label: 'Positioning devices > Thorax board > Position',
    changedBy: 'User, Test',
    oldValue: '',
    newValue: null,
    parameterNames: ['p6PositioningDevices'],
    task: 'CT simulation',
    updatedOn: '15-Mar-2021 15:16',
    kind: 'Modified',
  },
  {
    changedBy: 'User, Test',
    newValue: 'No',
    oldValue: null,
    parameterNames: ['p6BodyImplant'],
    task: '',
    updatedOn: '15-Mar-2021 13:56',
    label: 'Body implant',
    kind: 'Modified',
  },
  {
    label:
      'OAR contours > TRACHEA > Children > Criterion 1 > Primary goal dose (cGy)(RBE)',
    changedBy: 'User, Test',
    oldValue: '1800',
    newValue: '43',
    parameterNames: ['p6OARContours'],
    task: 'Physician intent',
    updatedOn: '15-Mar-2021 14:03',
    kind: 'Modified',
  },
  {
    label: 'OAR contours > TRACHEA > ROI color',
    changedBy: 'User, Test',
    oldValue: 'rgb(255, 150, 0)',
    newValue: 'rgb(192, 192, 192)',
    parameterNames: ['p6OARContours'],
    task: 'Physician intent',
    updatedOn: '15-Mar-2021 14:03',
    kind: 'Modified',
    valueCategory: 'RGB',
  },
  {
    label: 'OAR contours > TRACHEA > Primary goal dose (cGy)(RBE)',
    changedBy: 'User, Test',
    oldValue: '5250',
    newValue: '2344',
    parameterNames: ['p6OARContours'],
    task: 'Physician intent',
    updatedOn: '15-Mar-2021 14:03',
    kind: 'Modified',
  },
  {
    changedBy: 'User, Test',
    newValue:
      'NON-CLINICAL Lung high dose right image management (non-exporting)',
    oldValue: null,
    parameterNames: ['p6ProtocolCardName'],
    task: '',
    updatedOn: '15-Mar-2021 14:02',
    label: 'ProtocolCard name',
    kind: 'Modified',
  },
  {
    changedBy: 'User, Test',
    newValue: 'Urgent',
    oldValue: null,
    parameterNames: ['p6UrgencyLevel'],
    task: '',
    updatedOn: '15-Mar-2021 13:56',
    label: 'Urgency level',
    kind: 'Modified',
  },
  {
    changedBy: 'User, Test',
    newValue: 'No',
    oldValue: null,
    parameterNames: ['p6MedicalAllergies'],
    task: '',
    updatedOn: '15-Mar-2021 13:56',
    label: 'Medical allergies',
    kind: 'Modified',
  },
  {
    changedBy: 'User, Test',
    newValue: 'No',
    oldValue: null,
    parameterNames: ['p6Pregnant'],
    task: '',
    updatedOn: '15-Mar-2021 13:56',
    label: 'Pregnant',
    kind: 'Modified',
  },
  {
    changedBy: 'User, Test',
    newValue: 'Confirmed',
    oldValue: 'Not confirmed',
    parameterNames: ['p6PatientSetupUpToDate'],
    task: 'ct simulation',
    updatedOn: '18-Mar-2021 14:43',
    label: 'Patient setup is up to date for treatment',
    kind: 'Modified',
  },
  {
    changedBy: 'User, Test',
    newValue: 'No',
    oldValue: null,
    parameterNames: ['p6ContrastAllergy'],
    task: '',
    updatedOn: '15-Mar-2021 13:56',
    label: 'Contrast allergy',
    kind: 'Modified',
  },
  {
    changedBy: 'User, Test',
    newValue: 'No',
    oldValue: null,
    parameterNames: ['p6Pacemaker'],
    task: '',
    updatedOn: '15-Mar-2021 13:56',
    label: 'Pacemaker/ICD',
    kind: 'Modified',
  },
  {
    changedBy: 'User, Test',
    newValue: 'No',
    oldValue: null,
    parameterNames: ['p6UrinaryIncontinence'],
    task: '',
    updatedOn: '15-Mar-2021 13:56',
    label: 'Urinary incontinence',
    kind: 'Modified',
  },
];
